services:
  grobid:
    image: grobid/grobid:0.8.0
    init: true
    ports:
      - "8070:8070"
      - "8071:8071"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         # count: all
    #         device_ids: ['0']
    #         capabilities: [gpu]
  papermage-service:
    image: papermage-service:latest
    ports:
      - "5001:5001"
    environment:
      - AWS_ACCESS_KEY_ID=placeholder
      - AWS_SECRET_ACCESS_KEY=placeholder
      - AWS_DEFAULT_REGION=placeholder
      - ANTHROPIC_MODEL_ID=placeholder
  # ollama:
  #   image: ollama/ollama
  #   ports:
  #     - "11434:11434"
  #   command: serve && ollama pull llama3.1:70b && ollama run llama3.1:70b
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           # count: all
  #           device_ids: ['0']
  #           capabilities: [gpu]
  #   volumes:
  #     - ollama:/root/.ollama
    
  # semantic-scholar:
  #   image: ...
  # llm-service:
  #   image: ...
  # reviewer-service:
  #   image: ...
  # figure-critic-service:
  #   image: ...
  # reverse-proxy:
  #   image: nginx
  # frontend:
  #   image: ...

volumes:
  ollama:
    external: true