services:
  grobid:
    image: grobid/grobid:0.8.0
    init: true
    ports:
      - "8070:8070"
      - "8071:8071"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # count: all
            device_ids: ['0']
            capabilities: [gpu]
  # ollama:
  #   image: ollama/ollama
  #   ports:
  #     - "11434:11434"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           # count: all
  #           device_ids: ['0']
  #           capabilities: [gpu]
  #   volumes:
  #     - ollama:/root/.ollama
    
  # semantic-scholar:
  #   image: ...
  # llm-service:
  #   image: ...
  # reviewer-service:
  #   image: ...
  # reverse-proxy:
  #   image: nginx
  # frontend:
  #   image: ...

volumes:
  ollama:
    external: true