# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: figure_critic.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66igure_critic.proto\x12\x0c\x46igureCritic\"\x17\n\x08helloMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x19\n\nhelloReply\x12\x0b\n\x03msg\x18\x01 \x01(\t2K\n\x0c\x46igureCritic\x12;\n\x05Hello\x12\x16.FigureCritic.helloMsg\x1a\x18.FigureCritic.helloReply\"\x00\x42:\n\x1dMAMORX.figure_critic_rpc.lab6\xa2\x02\x18MAMORX.figure_critic_rpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'figure_critic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035MAMORX.figure_critic_rpc.lab6\242\002\030MAMORX.figure_critic_rpc'
  _globals['_HELLOMSG']._serialized_start=37
  _globals['_HELLOMSG']._serialized_end=60
  _globals['_HELLOREPLY']._serialized_start=62
  _globals['_HELLOREPLY']._serialized_end=87
  _globals['_FIGURECRITIC']._serialized_start=89
  _globals['_FIGURECRITIC']._serialized_end=164
# @@protoc_insertion_point(module_scope)
