# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: figure_critic.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66igure_critic.proto\x12\x15\x66igure_critic_service\"@\n\x10\x61rticleToAnalyze\x12\x0b\n\x03pdf\x18\x01 \x01(\x0c\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08\x61\x62stract\x18\x03 \x01(\t\";\n\x14\x66igureAnalysisResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nassessment\x18\x02 \x01(\t2\x83\x01\n\x13\x46igureCriticService\x12l\n\x14\x41ssessArticleFigures\x12\'.figure_critic_service.articleToAnalyze\x1a+.figure_critic_service.figureAnalysisResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'figure_critic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ARTICLETOANALYZE']._serialized_start=46
  _globals['_ARTICLETOANALYZE']._serialized_end=110
  _globals['_FIGUREANALYSISRESULT']._serialized_start=112
  _globals['_FIGUREANALYSISRESULT']._serialized_end=171
  _globals['_FIGURECRITICSERVICE']._serialized_start=174
  _globals['_FIGURECRITICSERVICE']._serialized_end=305
# @@protoc_insertion_point(module_scope)
