# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: figure_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'figure_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66igure_service.proto\x12\x0e\x66igure_service\":\n\nsendPDFMsg\x12\x0b\n\x03pdf\x18\x01 \x01(\x0c\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08\x61\x62stract\x18\x03 \x01(\t\"0\n\x0bpdfResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08response\x18\x02 \x01(\t2Y\n\x13\x66igureCriticService\x12\x42\n\x07SendPDF\x12\x1a.figure_service.sendPDFMsg\x1a\x1b.figure_service.pdfResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'figure_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDPDFMSG']._serialized_start=40
  _globals['_SENDPDFMSG']._serialized_end=98
  _globals['_PDFRESPONSE']._serialized_start=100
  _globals['_PDFRESPONSE']._serialized_end=148
  _globals['_FIGURECRITICSERVICE']._serialized_start=150
  _globals['_FIGURECRITICSERVICE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
